color_scheme: light

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-default-layout

url: https://docs.madelineproto.xyz
logo: logo.png

twitter:
  username: DaniilGentili
  card: summary
  
author:
  twitter: DaniilGentili
  
include: [".well-known"]
repository: danog/madelineproto

aux_links_new_tab: true

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/danog/MadelineProtoDocs" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false